qdrant:
  mode: local
  host: localhost
  port: 6333
  memory: false
  collection_name: cni_documents
  vectors:
    size: 384
    distance: Cosine
  optimizers:
    default_segment_number: 2
    memmap_threshold: 20000
  on_disk: false
